# Welcome to Continue!
# `main.py` and `sum.py` have been opened to show you the basics of debugging an error with Continue.
# Try running the example with `python3 ~/.vscode/extensions/basin.continue-0.0.1/examples/python/main.py`

from sum import sum

first = 1
second = "two"

sum(first, second)